### PR TITLE
Resolve code issue with commit ffaeabbd... where functionality appear…

### PR DESCRIPTION
**Pull request by its-michaelroy**
Restored Order by functionality for Youtube Videos

### CODE REVIEW

**Review by DeeJaeMann — CHANGES_REQUESTED** [review]
Edits look good.
Please ensure the merge conflicts are resolved with the updated main.

**Comment by its-michaelroy** [comment]
Resolved issue with conflict

**Review by dagaither — CHANGES_REQUESTED** [review]
These are the lines needed:

import { Button } from "reactstrap";
(Remove Button from the react-bootstrap import)

<Modal.Header closeButton style={{ backgroundColor: "#3b7f82" }}>
            <Modal.Title style={{ color: "#ffffff" }}>

<Modal.Body style={{ backgroundColor: "#2f2f2f" }}>

**Comment by its-michaelroy** [comment]
Styling has been included within Modals.

**Review by dagaither — APPROVED** [review]
Looks good 👍

**Review by DeeJaeMann — APPROVED** [review]
Looks like merge conflicts are good

**Pull request merged**
