### PR TITLE
10 build demo slot component

### LINKED ISSUE #10: Build Demo Slot Component

### PR DESCRIPTION
**Pull request by nekablair**
## What type of PR is this? (check all applicable)

- [X] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Other (please specify here: <type here>)
  
  
## Description of what this Pull Request does
Generates Demo list of students and allows instructor to change their status and update the database with that change.

## Related Tickets & Documents
- Closes #10 
- Related Issues: (enter ticket numbers here)
  
## QA Instructions, Screenshots, Recordings
Please look over logic and update styling per David's choices.
Also please note, I had merge conflicts when pulling from main, they should have been resolved, but wanted whomever reviews to be aware.
updatedemostatus

  
## Added/updated tests?
- [ ] Yes
- [X] Not Yet, and here is why: tests being generated still
- [ ] I need help with tests
- [ ] No, and here is why: __explain here__

### CODE REVIEW

**Review by DeeJaeMann — APPROVED** [review]
I don't see any issues with this PR. I see Mike's changes in here.  They may already have been merged with main.  Please resolve the merge conflicts.

**Comment by nekablair** [comment]
@dagaither we don't have to try and pull up the next student name, I stopped before doing that, I wanted to be sure it was working well and met the MVP criteria. Please feel free to remove that portion, thanks. Also, could you let me know when the PR is merged, that way I can put something in our channel. TIA!

**Comment by dagaither** [comment]
@nekablair Checking now

**Comment by dagaither** [comment]
Looks good 👍 .  For styling I can probably reuse code and format it like /rollcall/ using similar color coding (green - complete, grey - todo, yellow/orange - on deck) then also implement similar sorting function.  Does that sound good?

**Comment by nekablair** [comment]
That actually sounds great @dagaither thanks

**Review by dagaither — APPROVED** [review]
Merging

**Comment by dagaither** [comment]
Great, NP!

**Pull request merged**
