### PR TITLE
Refactored Demo to match RollCall

### LINKED ISSUE #125: Enhancement - Refactor Demo Layout/Style To Match RollCall

### PR DESCRIPTION
**Pull request by dagaither**
## What type of PR is this? (check all applicable)

- [ ] Feature
- [x] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Other (please specify here: <type here>)
  
  
## Description of what this Pull Request does
 * Updates student card layout / style to match RollCall.
 * Auto sorts by status ('on deck', 'to do', 'complete').
 * Adds Cohort dropdown selection.
 * Adds Random On Deck button.
 * If student manually set to 'on deck' replaces existing 'on deck'.
 * Modifies Reset button to match style.

## Related Tickets & Documents
- Closes #125

### CODE REVIEW

**Comment by dagaither** [comment]
@nekablair it wasn't my intention to gut large portions of your code, but, in the interest of time and efficiency I did a lot of prompt engineering with ChatGPT for the refactor.  Getting some of the dynamic sorting and updating functionality working required some changes that let AI do the heavy lifting for.  This resulted in some of the large red blocks you'll see in Files Changed.  

Please review and let me know if anything looks off or you're unhappy with any stuff that was removed and we can refactor again.  That said, it should be working nicely 😄

**Comment by dagaither** [comment]
Also, I just found a bug with the Random On Deck button so stand by for additional push.

**Comment by dagaither** [comment]
Bug is fixed and pushed.  I'm heading to bed but it will be ready for you all to review tomorrow or whenever you're available.

**Review by DeeJaeMann — APPROVED** [review]
This looks good.
@nekablair if you're good with the changes go ahead and merge this.

**Review by nekablair — APPROVED** [review]
LGTM!

**Pull request merged**
